<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\StockPilotWMS.Sharedkernel\StockPilotWMS.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Entities\" />
    <Folder Include="Enums\" />
    <Folder Include="Events\" />
    <Folder Include="Exceptions\" />
    <Folder Include="Rules\" />
    <Folder Include="ValueObjects\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
